refactor to core18 and gnome-3-28

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -1,6 +1,7 @@
 name: photoscape
-version: 3.7
-summary: photoscape
+title: Photoscape
+version: "3.7"
+summary: PhotoScape is a fun and easy photo editing software to fix and enhance photos.
 description: |
   PhotoScape is a fun and easy photo editing software that enables you to fix and enhance photos.
 
@@ -21,249 +22,186 @@ description: |
     - Paper Print: Print lined, graph, music and calendar paper
     - Face Search: Find similar faces on the Internet
 grade: stable
+
+base: core18
 confinement: strict
+
 architectures:
   - build-on: amd64
-    run-on: [amd64, i386]
+
+environment:
+  INSTALL_EXE: "$SNAP/PhotoScapeSetup_V3.7.exe"
+  INSTALL_FLAGS: "/S"
+  # TRICKS: "corefonts fontsmooth=rgb gdiplus vcrun2008"
+  TRICKS: "gdiplus_winxp"
+  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
+  DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
+  LC_ALL: "C.UTF-8"
+  SNAP_TITLE: "$SNAPCRAFT_PROJECT_SUMMARY"
+  SNAP_ICON: "$SNAP/meta/gui/icon.png"
+  SNAP_SUPPORT_URL: "https://github.com/snapcrafters/photoscape/issues"
 
 apps:
   photoscape:
-    command: bin/sommelier "$WINEPREFIX/drive_c/Program Files/PhotoScape/PhotoScape.exe"
-    environment:
-      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
-      DLLOVERRIDES: "mscoree,mshtml=;gdiplus=n,b"
-      INSTALL_PATH: "$SNAP/snap/installer/PhotoScapeSetup_V3.7.exe"
-      LC_ALL: "C.UTF-8"
-      TRICKS: "fontsmooth=rgb gdiplus vcrun2008"
+    extensions: [ gnome-3-28 ]
+    command: bin/start-photoscape
     plugs:
-      - desktop
-      - desktop-legacy
       - hardware-observe
       - home
-      - joystick
       - network
       - network-bind
-      - opengl
-      - pulseaudio
-      - removable-media
-      - wayland
-      - x11
+      - process-control
   wineboot:
     command: bin/sommelier $SNAP/bin/wineboot
-    environment:
-      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
-      DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
     plugs:
       - desktop
       - desktop-legacy
-      - pulseaudio
       - wayland
       - x11
   winecfg:
     command: bin/sommelier $SNAP/bin/winecfg
-    environment:
-      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
-      DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
     plugs:
       - desktop
       - desktop-legacy
-      - pulseaudio
       - wayland
       - x11
   winetricks:
     command: bin/sommelier $SNAP/bin/winetricks prefix="$WINEPREFIX"
-    environment:
-      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
-      DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
-      LC_ALL: "C.UTF-8"
     plugs:
       - desktop
       - desktop-legacy
       - network
-      - pulseaudio
+      - audio-playback
       - wayland
       - x11
 
 parts:
-  enable-i386:
+  installer:
+    plugin: dump
+    source: installer
+  add-repos:
     plugin: nil
-    build-attributes:
-      - no-system-libraries
-    build-packages:
-      # This snap is build on amd64 only
-      - on amd64:
-        - apt
-        - dpkg
-      - else fail
     override-build: |
-      snapcraftctl build
-      dpkg --add-architecture i386
-      apt update
-
-  wine:
-    plugin: nil
-    build-attributes:
-      - no-system-libraries
+      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
+        dpkg --add-architecture i386
+        apt update
+      fi
+      wget -nc https://dl.winehq.org/wine-builds/winehq.key
+      wget -nc https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key
+      apt-key add winehq.key
+      apt-key add Release.key
+      rm -f winehq.key Release.key
+      add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
+      add-apt-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./'
     build-packages:
-      - dpkg
+      - software-properties-common
       - wget
-    override-build: |
-      snapcraftctl build
-
-      WINE_REL="wine-staging"
-      WINE_ARCH="i386"
-      WINE_VER="3.10.0"
-
-      # wget and dpkg extract the wine debs
-      DEB_URLS="https://dl.winehq.org/wine-builds/ubuntu/pool/main/${WINE_REL}-${WINE_ARCH}_${WINE_VER}~xenial_${WINE_ARCH}.deb \
-                https://dl.winehq.org/wine-builds/ubuntu/pool/main/${WINE_REL}_${WINE_VER}~xenial_${WINE_ARCH}.deb"
-
-      for DEB_URL in ${DEB_URLS}; do
-        DEB=$(basename "${DEB_URL}")
-        echo "Downloading ${DEB_URL}..."
-        wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
-        echo "Unpacking ${DEB}..."
-        dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
-        rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
-      done
-
-      # Organise
-      cp -a ${SNAPCRAFT_PART_INSTALL}/opt/${WINE_REL}/* ${SNAPCRAFT_PART_INSTALL}/
-
-      # Cleanup
-      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt
-      rm -rf ${SNAPCRAFT_PART_INSTALL}/share/applications
-      rm -rf ${SNAPCRAFT_PART_INSTALL}/share/man
-      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/doc
-      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/lintian
-    after:
-      - enable-i386
 
   wine-runtime:
     plugin: nil
-    build-attributes:
-      - no-system-libraries
     stage-packages:
-      ### Depends from wine-devel-i386_x.y.z~xenial_i386.deb debian/control
-      - libasound2:i386
-      - libc6:i386
-      - libglib2.0-0:i386
-      #- libgphoto2-6:i386
-      - libgstreamer-plugins-base1.0-0:i386
-      - liblcms2-2:i386
-      - libldap-2.4-2:i386
-      - libmpg123-0:i386
-      - libncurses5:i386
-      - libopenal1:i386
-      - libpcap0.8:i386
-      - libpulse0:i386
-      - libudev1:i386
-      - libxext6:i386
-      - libxml2:i386
-      - zlib1g:i386
-      ### Recommends from wine-devel-i386_x.y.z~xenial_i386.deb debian/control
-      #- libcapi20-3:i386
-      #- libcups2:i386
-      - libdbus-1-3:i386
-      - libfontconfig1:i386
-      - libfreetype6:i386
-      - libglu1-mesa:i386
-      - libgnutls30:i386
-      - libgsm1:i386
-      - libgssapi-krb5-2:i386
-      - libjpeg8:i386
-      #- libodbc1:i386
-      - libosmesa6:i386
-      - libpng12-0:i386
-      #- libsane:i386
-      - libsdl2-2.0-0:i386
-      - libtiff5:i386
-      - libv4l-0:i386
-      - libvulkan1:i386
-      - libxcomposite1:i386
-      - libxcursor1:i386
-      - libxfixes3:i386
-      - libxi6:i386
-      - libxinerama1:i386
-      - libxrandr2:i386
-      - libxrender1:i386
-      - libxslt1.1:i386
-      - libxxf86vm1:i386
-      # Required for authentication - Observed in Steam and Track Mania
-      - winbind:i386
+      # - samba-libs
+      # - winbind
+      ## wine
+      - wine-stable:i386
+      ## Required for authentication - Observed in Steam and Track Mania
       - samba-libs:i386
-    override-build: |
-      snapcraftctl build
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init.d
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/logrotate.d
-      rm -rf $SNAPCRAFT_PART_INSTALL/lib/x86_64-linux-gnu
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/applications
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
+      - winbind:i386
+    stage:
+      - -etc/init
+      - -etc/init.d
+      - -etc/logrotate.d
+      - -usr/share/apps
+      - -usr/share/applications
+      - -usr/share/bug
+      - -usr/share/doc
+      - -usr/share/doc-base
+      - -usr/share/debhelper
+      - -usr/share/lintian
+      - -usr/share/man
+      - -usr/share/pixmaps
+      - -usr/share/pkgconfig
     after:
-      - enable-i386
+      - add-repos
 
   sommelier:
     plugin: dump
-    build-attributes:
-      - no-system-libraries
-    source: snap/scripts
+    source: scripts
     organize:
+      'snap-*': bin/
       'sommelier': bin/
       'winetricks': bin/
       'zenity': bin/
+      'start-photoscape': bin/
+    build-packages:
+      - curl
     stage-packages:
-      - cabextract:i386         # winetricks
-      - libgdk-pixbuf2.0-0:i386 # yad
-      - libgtk-3-0:i386         # yad
-      - libnotify4:i386         # yad
-      - libnotify-bin:i386      # sommelier
-      - perl-base:i386          # winetricks
-      - shared-mime-info:i386
-      - unzip:i386              # winetricks
-      - wget:i386               # winetricks
-      - x11-xserver-utils:i386  # sommelier
-      - yad:i386                # winetricks
-    override-build: |
-      snapcraftctl build
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init.d
-      rm -rf $SNAPCRAFT_PART_INSTALL/etc/logrotate.d
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/fc-*
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/gtk-*
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/dconf/dconf-service
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/glib-networking/glib-pacrunner
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/GConf
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/aclocal
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apport
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bash-completion
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Adwaita
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Humanity*
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/LoginIcons
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/ubuntu-mono*
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/info
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/kde4
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/menu
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/perl5
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
-      rm -rf $SNAPCRAFT_PART_INSTALL/lib/x86_64-linux-gnu
-      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu
+      - cabextract         # winetricks
+      - libnotify4         # yad
+      - libnotify-bin      # sommelier
+      - perl-base          # winetricks
+      - rsync
+      - shared-mime-info
+      - unzip              # winetricks
+      - wget               # winetricks
+      - yad                # winetricks
+      - x11-xserver-utils  # for xrandr to set virtual desktop
+    override-pull: |
+      snapcraftctl pull
+
+      curl --silent --show-error --location "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -o winetricks
+      chmod +x winetricks
+    stage:
+      - -etc/init
+      - -etc/init.d
+      - -etc/logrotate.d
+      - -usr/bin/fc-*
+      - -usr/bin/gtk-*
+      - -usr/lib/dconf/dconf-service
+      - -usr/lib/glib-networking/glib-pacrunner
+      - -usr/share/GConf
+      - -usr/share/aclocal
+      - -usr/share/apport
+      - -usr/share/apps
+      - -usr/share/bash-completion
+      - -usr/share/bug
+      - -usr/share/debhelper
+      - -usr/share/doc
+      - -usr/share/doc-base
+      - -usr/share/icons/Adwaita
+      - -usr/share/icons/Humanity*
+      - -usr/share/icons/LoginIcons
+      - -usr/share/icons/ubuntu-mono*
+      - -usr/share/info
+      - -usr/share/kde4
+      - -usr/share/lintian
+      - -usr/share/menu
+      - -usr/share/man
+      - -usr/share/perl5
+      - -usr/share/pixmaps
+      - -usr/share/pkgconfig
     after:
-      - enable-i386
+      - add-repos
+
+  # This part removes all the files in this snap which already exist in
+  # connected content and base snaps. Since these files will be available
+  # at runtime from the content and base snaps, they do not need to be
+  # included in this snap itself.
+  #
+  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
+  #
+  cleanup:
+    after:  # Make this part run last; list all your other parts here
+      - installer
+      - add-repos
+      - wine-runtime
+      - sommelier
+    plugin: nil
+    build-snaps:  # List all content-snaps and base snaps you're using here
+      - core18
+      - gnome-3-28-1804
+    override-prime: |
+      set -eux
+      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
+        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
+      done
